AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  newlambdaserverless:
     Type: 'AWS::Serverless::Function'
     Properties:
     Handler: newlambdaserverless.handler
     Runtime: nodejs6.10
     CodeUri: s3://staticcontentforsam/serverless-webapp-master.zip
     Role: 'arn:aws:iam::896715882735:role/MyLambdaRole'    
  newtable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: EmailID
          AttributeType: S
        - AttributeName: BloodGroup
          AttributeType: S
        - AttributeName: Designation
          AttributeType: S
        - AttributeName: FirstName
          AttributeType: S 
        - AttributeName: LastName
          AttributeType: S  
      KeySchema:
        - AttributeName: EmailID
          KeyType: HASH
 
     Events:
        getAZsAPI:
        Type: Api
        Properties:
          Path: /getazs
          Method: ANY
