AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
 myHelloTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: myHelloTable
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
   newlambdaserverless:
     Type: 'AWS::Serverless::Function'
     Properties:
     Handler: newlambdaserverless.handler
     Runtime: nodejs6.10
     CodeUri: s3://staticcontentforsam/serverless-webapp-master.zip
     Role: 'arn:aws:iam::896715882735:role/MyLambdaRole'      
     Events:
        getAZsAPI:
        Type: Api
        Properties:
          Path: /getazs
          Method: ANY
