AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TableAlerter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: s3://staticcontentforsam/serverless-webapp-master.zip
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: ANY
      Environment:
        Variables:
          REGION: us-east-1
        
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt Message.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON   
     Resources:
        NotesTable:
        Type: AWS::DynamoDB::Table
        Properties:
        TableName: Message
        AttributeDefinitions:
           - AttributeName: userId
             AttributeType: S
           - AttributeName: noteId
             AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
     
