AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  newtable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
	   KeySchema:
        - AttributeName: EmailID
          KeyType: HASH
      
  newlambdaserverless:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: newlambdaserverless.handler
      Runtime: nodejs6.10
      CodeUri: s3://staticcontentforsam/serverless-webapp-master.zip
      Role: 'arn:aws:iam::896715882735:role/MyLambdaRole'
      
      Events:
        Tablet1:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt newtable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 10
